# Generated by Django 5.1.4 on 2025-01-17 15:36

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="SkillPost",
            fields=[
                (
                    "post_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_name", models.CharField(max_length=500)),
                ("post_description", models.TextField(max_length=1000)),
                (
                    "post_media",
                    cloudinary.models.CloudinaryField(blank=True, max_length=255),
                ),
                ("post_tags", models.CharField(blank=True, max_length=100)),
                ("createdAt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tweets.user"
                    ),
                ),
            ],
        ),
    ]
