# Generated by Django 5.1.4 on 2025-01-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_alter_skillpost_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillpost",
            name="post_likes",
            field=models.IntegerField(default=0),
        ),
    ]
