# Generated by Django 5.1.4 on 2025-01-06 05:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_remove_user_id_user_user_id_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='peeptalks/profile_photo'),
        ),
    ]
